# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cdd661982f5d18f0bd84e4e42c8dc32a46517cc895e300b3e586c89039a29cd337b577a36ef1bdf4d4222b28114dc06cd40adde99e9b0171b5a106db9f86137

test:
  secret_key_base: fd5db88f1561a333f45bb273a3a763cfb9a81bd3535a5a18204bb95813ce16e135249374b02408379aba32f75404cb960f79bf87f3c359cdef5a5512dc05a98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
